---
- hosts: gitlab-runner
  become: true

  vars:
    - NUMBER_OF_CONCURRENT: 1
    - RUNNER_AUTHENTICATION_TOKEN: ""
    - GITLAB_URL: "https://gitlab.com/"

  tasks:
    - name: APT update
      apt:
        update_cache: yes

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - gnupg
        state: latest
        update_cache: false

    - name: Remove existing Docker GPG apt Key
      file:
        path: /etc/apt/keyrings/docker.gpg
        state: absent

    - name: Create directory for Docker GPG key
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download, install and convert Docker GPG key
      shell:
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

    - name: Set permissions for Docker GPG key
      file:
        path: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Add the repository to Apt sources
      shell: |
        echo \
          "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
          tee /etc/apt/sources.list.d/docker.list > /dev/null

    - name: APT update
      apt:
        update_cache: yes

    - name: Install require Docker packages
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: false

    - name: Add the Gitlab Runner official GitLab repository
      shell: |
        curl -L "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh" | sudo bash

    - name: Install gitlab runner
      apt:
        pkg:
          - gitlab-runner=16.5.0
        update_cache: yes

    - name: Add gitlab-runner user to docker group
      ansible.builtin.user:
        name: gitlab-runner
        group: docker

    - name: Register gitlab docker runner
      command: |
        gitlab-runner register \
        --non-interactive \
        --url {{ GITLAB_URL }} \
        --registration-token "{{ RUNNER_AUTHENTICATION_TOKEN }}" \
        --executor "docker" \
        --docker-image alpine:latest \
        --description "docker-runner" \
        --run-untagged="true" \
        --locked="false" \
        --access-level="not_protected"

    - name: Modify the "concurrent number" in /etc/gitlab-runner/config.toml file
      lineinfile:
        path: /etc/gitlab-runner/config.toml  # Specify the path 
        regexp: '^concurrent ='  # Replace KEY_NAME with the name of the key you want to change
        line: 'concurrent = {{ NUMBER_OF_CONCURRENT }}'  
      become: yes

    - name: Restart Gitlab Runner
      shell:
        gitlab-runner restart





