version: '3.8'

services:
  stats:
    image: bitnami/rabbitmq:3.11.26-debian-11-r1
    container_name: stats
    hostname: stats
    environment:
      - RABBITMQ_NODE_TYPE=stats
      - RABBITMQ_NODE_NAME=rabbit@stats
      - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
    ports:
      - '15672:15672'
    volumes:
      - 'rabbitmqstats_data:/bitnami/rabbitmq/mnesia'
    networks:
      - cluster-network

  queue-disc1:
    image: bitnami/rabbitmq:3.11.26-debian-11-r1
    container_name: queue-disc1
    hostname: queue-disc1
    environment:
      - RABBITMQ_NODE_TYPE=queue-disc
      - RABBITMQ_NODE_NAME=rabbit@queue-disc1
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@stats
      - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
    volumes:
      - 'rabbitmqdisc1_data:/bitnami/rabbitmq/mnesia'
    networks:
      - cluster-network

  queue-ram1:
    image: bitnami/rabbitmq:3.11.26-debian-11-r1
    container_name: queue-ram1
    hostname: queue-ram1
    environment:
      - RABBITMQ_NODE_TYPE=queue-ram
      - RABBITMQ_NODE_NAME=rabbit@queue-ram1
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@stats
      - RABBITMQ_ERL_COOKIE=s3cr3tc00ki3
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
    volumes:
      - 'rabbitmqram1_data:/bitnami/rabbitmq/mnesia'
    networks:
      - cluster-network

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    hostname: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "5672:5672"
      - "1936:1936"
    networks:
      - cluster-network

networks:
 cluster-network:
  driver: bridge

volumes:
  rabbitmqstats_data:
    driver: local
  rabbitmqdisc1_data:
    driver: local
  rabbitmqram1_data:
    driver: local
